In [4]:
import numpy as np

In [25]:
A = np.array([[1,1,1],
              [4,4,2],[2,1,-1]])
a = np.array([1,2,0])
A

array([[ 1,  1,  1],
       [ 4,  4,  2],
       [ 2,  1, -1]])

In [13]:
B =  np.array([[7,-7,1],[-3,3,2],[7,-7,-72]])
b =  np.array([1,2,7])

In [3]:
C = np.array([[1,2,3,4],[2,2,3,4],[3,3,3,4],[4,4,4,4]])
c = np.array([20,22,22,24])

NameError: name 'np' is not defined

In [14]:
T = np.array([[1,1,1],[4,4,2],[2,1,-1]])
T

array([[ 1,  1,  1],
       [ 4,  4,  2],
       [ 2,  1, -1]])

In [15]:
t = np.array([1,2,0])
t

array([1, 2, 0])

In [17]:
def sist_lin_tri_sup(A,b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

In [18]:
def elimin_pivotamento_parc(A,b):
    Ab = np.c_[A,b]
    quantL = len(Ab)
    for l in range(quantL):
        #verifica qual é o maior pivo
        pivo = np.absolute(Ab[l][l])
        linhaPivo = l
        for c in range(l+1,quantL):
            if np.absolute(Ab[c][l]) > pivo:
                pivo = np.absolute(Ab[c][l])
                linhaP = c
        #permuta as linhas    
        if(linhaP != l):
            Ab[[c,linhaP]] = Ab[[linhaP,c]]
        #eliminação gaussiana
        for c in range(quantL-1):
            for l in range(c+1,quantL):

                Ab[l] = Ab[l] - (Ab[l,c]/Ab[c,c])*Ab[c]
    #resolução da matriz
    x = sist_lin_tri_sup(Ab[:,:-1],Ab[:,-1])    
    return x


In [19]:
elimin_pivotamento_parc(T,t)

array([ 1., -1.,  1.])