# 1.1

In [2]:
import numpy as np

In [71]:
def classExist(A,b):
    rankA = np.linalg.matrix_rank(A)
    rankà = np.linalg.matrix_rank(np.c_[A,b])
    n = A.shape[1]
    if(rankA == rankà and rankA == n):
        print('Possível e determinado \nPossui uma solução')
    elif(rankA== rankà and rankA < n):
        print('Sistema possível e indeterminado \nPossui infitas soluções')
    elif(rankà > rankA):
        print('Sistemma Impossível \nNão adimite solução precisa')
    

In [17]:
A1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
b1 = np.array([1,1,1])
A2 = np.array([[2,3],[-4,-6]])
b2 = np.array([10,-10])

In [72]:
classExist(A1,b1)


Possível e determinado 
Possui uma solução


In [73]:
classExist(A2,b2)

Sistemma Impossível 
Não adimite solução precisa


# 1.2

In [30]:
 from scipy.linalg import solve_triangular

In [46]:
def sist_lin_tri_sup(A,b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
        print(x)
    return x

In [3]:
A3 = np.array([[3,4,-5,1],
               [0,1,1,-2],
               [0,0,4,-5],
               [0,0,0,2]])
B3 = np.array([-10,-1,3,2])                                                                   
                                                                         
                                                                         
                                                                         
A3
B3

array([-10,  -1,   3,   2])

In [48]:
sist_lin_tri_sup(A3,B3)

[nan nan  2.  1.]
[nan -1.  2.  1.]
[ 1. -1.  2.  1.]


array([ 1., -1.,  2.,  1.])

In [49]:
 solve_triangular(A3, B3, lower=False)


array([ 1., -1.,  2.,  1.])

# 1.3

In [51]:
def sist_lin_tri_inf(A,b):
    n = len(b)
    x = np.empty(n)
    x[0] = b[-1]/A[0, 0]
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
        print(x)
    return x

In [3]:
A4 = np.array([[3,0,0,0],
               [2,1,0,0],
               [1,0,1,0],
               [1,1,1,1]])


b4 = np.array([4,2,4,2])

In [55]:
sist_lin_tri_inf(A4,b4)

[0.66666667 0.66666667 3.33333333 2.66666667]
[0.66666667 0.66666667 3.33333333 2.66666667]
[ 0.66666667  0.66666667  3.33333333 -2.66666667]


array([ 0.66666667,  0.66666667,  3.33333333, -2.66666667])

In [61]:
solve_triangular(A4, b4, lower=True)


array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

# 1.4 . Obs: Não executa corretamente

In [63]:
def sist_lin_diagonal(A,b): return b/A.diagonal()

In [97]:
def sist_lin_tri_sup(A,b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

In [98]:
def sist_lin_tri_inf(A,b):
    n = len(b)
    x = np.empty(n)
    x[0] = b[-1]/A[0, 0]
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
    return x

In [121]:
def solu_geral(A,b):
    s = True
    inf = True
    for i in range(len(np.diag(A4))-1):
        aux = A4[i,i+1:]
        print(aux)
        print(np.array_equal(aux,np.zeros(aux.size)))
        if(np.array_equal(aux,np.zeros(aux.size))!= True):
           
            s = False
            break
    if(s):
        for i in range(len(np.diag(A4))-1):
            aux = A4[i+1:,i]
            if(np.array_equal(aux,np.zeros(aux.size))!= True):
                inf = False
                break
    if(s and inf):
        solu = sist_lin_diagonal(A,b)
        return solu
    elif(s):
        print('suo')
        solu = sist_lin_tri_sup(A,b)
        return solu
    else:
        print('inf')
        solu = sist_lin_tri_inf(A,b)
        return solu

In [127]:

A = np.diag([1,4,2])
B = np.array([4, 2, 2])


A1 = np.array([[3,0,0,0],
               [2,1,0,0],
               [1,0,1,0],
               [1,1,1,1]])


b1 = np.array([4,2,4,2])

A2 = np.array([[3,4,-5,1],
               [0,1,1,-2],
               [0,0,4,-5],
               [0,0,0,2]])
B2 = np.array([-10,-1,3,2])                                                                   
                                                                         


In [113]:
solu_geral(A1,b1)

aqi
inf


array([ 0.66666667,  0.66666667,  3.33333333, -2.66666667])

In [125]:
solu_geral(A2,B2)

[0 0 0]
True
[0 0]
True
[0]
True
suo


array([ 1., -1.,  2.,  1.])

In [128]:
solu_geral(A,B)

[0 0 0]
True
[0 0]
True
[0]
True
suo


array([4. , 0.5, 1. ])