In [9]:
import numpy as np

In [10]:
def lu(A):
    n = A.shape[0]
    piv = np.arange(0,n)
    U = A.copy()
    for k in range(n-1):
        ind_max_linha = np.argmax(abs(U[k:n,k])) + k
        piv[[k,ind_max_linha]] = piv[[ind_max_linha,k]]
        U[[k,ind_max_linha]] = U[[ind_max_linha,k]]
        for i in range(k+1,n):          
            U[i,k] = U[i,k]/U[k,k]      
            for j in range(k+1,n):      
                U[i,j] -= U[i,k]*U[k,j] 

    return [U,piv]

def sist_lin_tri_inf(L,b):
    for i in range(L.shape[0]): 
        for j in range(i):
            b[i] -= L[i,j]*b[j]
    return b

def sist_lin_tri_sup(U,y):
    for i in range(U.shape[0]-1,-1,-1): 
        for j in range(i+1, U.shape[1]):
            y[i] -= U[i,j]*y[j]
        y[i] = y[i]/U[i,i]
    return y

**Letra A**

In [11]:
A = np.array([[1, 1, 1], [4, 4, 2], [2, 1., -1]])
b = np.array([1, 2, 0.])

LU, piv = lu(A)                      
b = b[piv]
y = sist_lin_tri_inf( LU, b )
x = sist_lin_tri_sup(  LU, y )
x

array([ 1., -1.,  1.])

In [12]:
A@x

array([1., 2., 0.])

**Letra B**

In [13]:
A = np.array([[7, -7, 1], [-3, 3, 2], [7, 7., -72]])
b = np.array([1, 2, 7.])

LU, piv = lu(A)                      
b = b[piv]
y = sist_lin_tri_inf( LU, b )
x = sist_lin_tri_sup(  LU, y )
x

array([5.64285714, 5.64285714, 1.        ])

In [14]:
A@x

array([1., 2., 7.])

**Letra C**

In [15]:
A = np.array([[1, 2, 3, 4], [2, 2, 3, 4], [3, 3., 3, 4], [4, 4, 4, 4]])
b = np.array([20, 22, 22., 24])

LU, piv = lu(A)                      
b = b[piv]
y = sist_lin_tri_inf( LU, b )
x = sist_lin_tri_sup(  LU, y )
x

array([ 2., -2.,  2.,  4.])

In [16]:
A@x

array([20., 22., 22., 24.])